### ISSUE TITLE
Generated type file disregards channel name, falls back to 'AnonymousMessage1'

### ISSUE THREAD

**Issue by myftija** [jonaslagoni/asyncapi-quicktype-template#12]
Hi,

I was trying to generate Typescript interfaces out of AsyncAPI specs, but I came across a seemingly erroneous behaviour. The contents of the generated interfaces are correct and follow the schema, but the generated interface name is `AnonymousMessage1`, which is incorrect. Same goes for the file name: `AnonymousMessage1.ts`. Am I missing something, or is it a bug?

**Comment by jonaslagoni** [comment]
Hey @myftija 

The template does not really care about channels, but the messages alone. So to change the naming of the file change/add the `name` property of the message object.

```
channels:
  test:
    publish:
      message:
        name: "TestName"
```
Would generate a file called `TestName`.

**Comment by myftija** [comment]
Hey @jonaslagoni, 

thanks for the quick response, appreciated!

I have another question, maybe a bit unrelated to this topic, but I thought I'd ask anyway. Would you recommend using `@asyncapi/generator` in combination with this template to generate typescript interfaces, or rather using [generator-model-sdk](https://github.com/asyncapi/generator-model-sdk)?

**Comment by jonaslagoni** [comment]
It kinda depends @myftija on your setup. We do not have any direct template wrapper or CLI for the model generation library yet (which is why I assume you are using this template instead). So there is no "easy" one-liner you can use to generate your models, for now at least.

This means that you would have to create your own js files to interact with it, which some might not want to, or you could create your own template wrapper (maybe even open-source it? 😉) to allow this.

If you need any help with the libraries you can always reach out on the [AsyncAPI slack](https://asyncapi.com/slack-invite).

**Comment by myftija** [comment]
Alright, thanks for the input @jonaslagoni :)
